LOG_LEVEL: info
MISSION_CONTROL_PORT: 4000
ROS_BRIDGE_URL: ws://localhost:9090
MISSION_CONTROL_HOST: 192.168.68.200
RABBIT_MQ_HOST: 192.168.68.200
IFACE_NAME: wlan0 #wlP7p1s0
MAC: "58:02:05:0d:2b:ca" #"58:02:05:0c:a9:9c"
AMR: fork
