MISSION_CONTROL_PORT: 4000
ROS_BRIDGE_URL: ws://localhost:9090
IFACE_NAME:
  enp3s0
  # eno1
  #enp9s0 ruifang
  # enp0s31f6
INITIAL_BATTERY_PERCENTAGE: 0.8
BATTERY_LIFE: 3 # hours
CHARGE_TIME: 0.008 # hours
LOG_LEVEL: info
# enp9s0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
#         inet 169.254.232.127  netmask 255.255.0.0  broadcast 169.254.255.255
#         inet6 fe80::e4e:93cf:f480:18ad  prefixlen 64  scopeid 0x20<link>
#         ether 78:d0:04:2c:d7:bb  txqueuelen 1000  (Ethernet)
#         RX packets 263079  bytes 269485966 (269.4 MB)
#         RX errors 0  dropped 0  overruns 0  frame 0
#         TX packets 225  bytes 185 6 (18.5 KB)
#         TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
#         device memory 0xb3200000-b327ffff
